WIFI_SSID = "[CHANGE_ME]"
WIFI_PW = "[CHANGE_ME]"

LOCATION = "[ROOMNAME]"

PIN_SENSOR = 2
PIN_SDA = 4
PIN_SCL = 5

OLED_WIDTH = 64
OLED_HEIGHT = 48

BLINK_TIMEOUT = 0.05
SLEEP_INTERVAL = 60

DB_URI = "http://seriesly.local:3133/sensors"
